// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhyJ-WpNnwq5I9B0NAx7SGvD4ywjTRCnw',
    appId: '1:1036526004206:web:c9322351606380e0da50ff',
    messagingSenderId: '1036526004206',
    projectId: 'rocky-birdwick-database',
    authDomain: 'rocky-birdwick-database.firebaseapp.com',
    storageBucket: 'rocky-birdwick-database.appspot.com',
    measurementId: 'G-664DETEGH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXy97yeUiGdSGL84XR9iFu7f5BSpQq4bY',
    appId: '1:1036526004206:android:c8c5debb0d94cb10da50ff',
    messagingSenderId: '1036526004206',
    projectId: 'rocky-birdwick-database',
    storageBucket: 'rocky-birdwick-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIyIlsokTYbYlv3Ati_uK4FJcrYhghhVw',
    appId: '1:1036526004206:ios:2f5ac8e77c9ed5e4da50ff',
    messagingSenderId: '1036526004206',
    projectId: 'rocky-birdwick-database',
    storageBucket: 'rocky-birdwick-database.appspot.com',
    iosClientId: '1036526004206-i8v0se89qp827loqu9679n3sm5u512if.apps.googleusercontent.com',
    iosBundleId: 'com.example.rockyBirdwick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIyIlsokTYbYlv3Ati_uK4FJcrYhghhVw',
    appId: '1:1036526004206:ios:2f5ac8e77c9ed5e4da50ff',
    messagingSenderId: '1036526004206',
    projectId: 'rocky-birdwick-database',
    storageBucket: 'rocky-birdwick-database.appspot.com',
    iosClientId: '1036526004206-i8v0se89qp827loqu9679n3sm5u512if.apps.googleusercontent.com',
    iosBundleId: 'com.example.rockyBirdwick',
  );
}
